Grasshopper
zheleznovux/rubius-hw pull request #1
Opened 2021-02-28 16:43 UTC by zheleznovux

2021-03-03 06:24 UTC, studenttsu requested changes
Привет) В целом очень даже хороший результат!

Оставил комментарии и есть общая рекомендация - используй более простые имена классов, про принцип именования поговорили в семинаре про БЭМ, нужно в следующем спринте порефакторить код, чтобы было проще читать!

`.main_aboutUs_content_left_desc` - принято слова отделять `-` и не использовать camelCase в html

Осталось немного - поправить текущие комментарии и работа первого спринта будет принята)

2021-03-03 06:24 UTC, studenttsu commented on 2pt/index.html
> +          <img src="images/instagram.png" alt="instagram" />
нужно иконкци соц сетей сделать ссылкой, внутрь ссылки картинку

2021-03-03 06:24 UTC, studenttsu commented on 2pt/index.html
> +          <button class="header_main_content_btn">
кнопку можно будет переиспользовать, лучше описать самостоятельным именем класса

обычная практика называть имя класса кнопки как .btn

2021-03-03 06:24 UTC, studenttsu commented on 2pt/index.html
> +              <img src="images/video.png" alt="video" />
этот элемент нужно сверстать не просто картинкой, ведь в будущем мы можем захотеть поменять фон)

по наведению хорошо бы сделать анимацию, к примеру увеличение масштаба фона или размера иконки play

2021-03-03 06:24 UTC, studenttsu commented on 2pt/main.css
> +  font-size: 12px;
вижу, что элементам футера во многих местах указываете font-size: 12px

достаточно контейнеру .footer задать свойство размера текста, дочерние элементы унаследуют это свойство

такой подход лучше, чтобы не заниматься copy-paste одинаковых свойств

Так же истори и с цветом текста.

Font-weight по умолчанию normal (если не переипределили на верхнем уровне), поэтому специально задавать это свойство не обязательно

2021-03-03 06:24 UTC, studenttsu commented on 2pt/index.html
> +        <span>Услуги и цены</span>
здесь тоже нужно использовать теги ссылок
обычно реализуют списком `ul`

2021-03-09 09:16 UTC, studenttsu requested changes
Привет! Много чего поправлено, спасибо!

Но остался важный момент, который нужно дожать. Это нарушение принципа именования по БЭМ, изучи ещё раз плиз документацию https://ru.bem.info/methodology/quick-start/

2021-03-09 09:16 UTC, studenttsu commented on 2pt/index.html
> +      <nav class="header__nav">
`нужно поправить`

а где родительский класс блока? это нарушение принципа методологии БЭМ - нужно поправить по всему коду

![image](https://user-images.githubusercontent.com/12005449/110447065-6fbc8980-80f2-11eb-997d-8ac0e8b608cb.png)

2021-03-10 04:10 UTC, studenttsu requested changes
уже лучше! нужно всё-таки дожать разметку по БЭМ, чтобы окончательно с этим разобраться

2021-03-10 04:10 UTC, studenttsu commented on 2pt/src/index.html
> +          <div class="main__item">
этот блок удобней назвать своим именем, к примеру benefit. И дальше лучше декомпозировать большие блоки на более мелкие. Так код удобней поддерживать и читать

```
.benefit
.benefit__icon
.benefit__title
.benefit__description

```

2021-03-10 04:10 UTC, studenttsu commented on 2pt/src/index.html
> +            <div class="content__desc">
`content__des`

остались участки кода в подвешенном состоянии, оторванные от блока .content

2021-03-10 04:27 UTC, zheleznovux commented on 2pt/src/index.html
> +          <div class="main__item">
Таким же образом можно блок .content переименовать?

2021-03-10 04:32 UTC, studenttsu approved these changes
удачи в работе след. спринта)

2021-03-10 04:46 UTC, merged