Grasshopper2
zheleznovux/rubius-hw pull request #2
Opened 2021-03-11 20:11 UTC by zheleznovux

- Вёрстка макета с применением БЭМ методологии, блоки:
    - Популярные услуги
    - Услуги и цены
    - Мастера
- Использование препроцессора SASS в нотации SCSS
- Подключить Gulp, собрать вёрстку

Начал делать адаптивную шапку и понял, что придётся всё адаптировать, чтобы не затягивать с этим спринтом на 3 спринт перенес это задание.

2021-03-13 10:17 UTC, studenttsu requested changes
Большая работа, спасибо! Крутой эффект наведения на девушку)

Нужно поправить важные моменты, описал в комментах. 
Так же стоит разобраться с сеткой - сейчас не по макету.

![image](https://user-images.githubusercontent.com/12005449/111026993-0608ec00-8420-11eb-91ca-266790de2967.png)

2021-03-13 10:17 UTC, studenttsu commented on src/index.html
> +          <button class="btn btn-large">
`нужно поправить`

Не стоит забывать, что для модификаторов используется нижнее подчёркивание.

`.btn_large`

2021-03-13 10:17 UTC, studenttsu commented on src/index.html
> +            <img class="master__img" class="master__icon" src="images/master1.png" alt="">
`нужно поправить`

Вставил картинку много больше размера блока и вёрстка поплыла, нам нужно тестировать вёрстку на "переполнение". Картинка может быть какой-угодно.
В других местах тоже обрати на это внимание и поправь. Та же ситуация и с текстом.

![image](https://user-images.githubusercontent.com/12005449/111026705-410a2000-841e-11eb-85d0-9e311672fa33.png)

2021-03-13 10:17 UTC, studenttsu commented on src/index.html
> +            <img class="master__img" class="master__icon" src="images/master1.png" alt="">
master__icon - не совсем корректное название - не соответствует содержимому

2021-03-13 10:17 UTC, studenttsu commented on src/index.html
> +
Нужно выбрать один принцип задания отстпутов.
Не совсем понятно зачем 4 пустых строки?

Так же между многострочными блоками лучше вставлять пустую строку, чтобы дать "воздуха" - так намного легче читать код)

2021-03-13 10:17 UTC, studenttsu commented on src/scss/main.scss
>  @import url("https://fonts.googleapis.com/css2?family=Montserrat&display=swap");
нужно ещё указывать и начертания, сейчас у тебя в результате font-weight везде 400, хотя в коде указаны верно

2021-03-13 10:17 UTC, studenttsu commented on src/scss/main.scss
> +$main-color: #333333;
переменные лучше вынести в отдельный файл - можно будет потом переиспользовать в других файлах стилей

2021-03-13 10:17 UTC, studenttsu commented on src/scss/main.scss
> +.header__logo {
`нужно поправить`

У нас же есть препроцессор, вложенность позволить писать более компактный код. Наведи плиз порядок в коде)

.header {
  &__logo {
    ...
  }

  &__nav {
    ..
  }
}

2021-03-18 11:45 UTC, zheleznovux commented on src/scss/main.scss
> +$main-color: #333333;
Вынес в отдельный файл _var.scss

2021-03-18 12:25 UTC, studenttsu approved these changes
Отлично!

2021-03-18 14:09 UTC, merged